terminate called after throwing an instance of 'std::runtime_error'
  what():  Voronoy container error at start() method!
